version: "3.8"

networks:
  database-net:
  proxy-network:
    external: true
    name: proxy-network

services:
  scraper:
    build:
      context: .
    depends_on:
      - postgres-db
    restart: unless-stopped
    networks:
      - database-net

    environment:
      DB_HOST: "postgres-db"
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_PORT: ${DB_PORT}
      DB_PASSWORD: ${DB_PASSWORD}
      TZ: "Europe/Brussels"

  webserver:
    build:
      context: ./Corap-web/.
    command: ./app -listen "0.0.0.0" -prod
    depends_on:
      - postgres-db
    restart: unless-stopped
    networks:
      - database-net
      - proxy-network
    ports:
      - "3000:3000"
    environment:
      DB_HOST: "postgres-db"
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_DATABASE}
      DB_PORT: ${DB_PORT}
      ANALYTICS: ${ANALYTICS}
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"

  postgres-db:
    image: postgres:15.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "9979:5432"
    networks:
      - database-net
    volumes:
      - db:/var/lib/postgresql/data
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"

volumes:
  db:
